import { StyleSheet } from 'react-native';

import { BrandPalette, FontFamilies, type ThemeColors } from '@/constants/theme';

/** Largura a partir da qual a lista mostra todas as colunas, como no tablet deitado. */
export const WIDE_LAYOUT_MIN_WIDTH = 900;

export function createHomeStyles(theme: ThemeColors) {
  const label = {
    color: theme.textSecondary,
    fontFamily: FontFamilies.semibold,
    fontSize: 11,
    fontWeight: '600' as const,
    letterSpacing: 0.9,
  };
  const button = {
    minHeight: 48,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    paddingHorizontal: 20,
    borderRadius: 14,
  };

  return StyleSheet.create({
    safeArea: { flex: 1, backgroundColor: theme.background },
    topBar: {
      minHeight: 72,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      flexWrap: 'wrap',
      rowGap: 8,
      paddingHorizontal: 20,
      paddingVertical: 12,
      backgroundColor: theme.surface,
      borderBottomWidth: 1,
      borderBottomColor: theme.border,
    },
    topBarWide: { paddingHorizontal: 40 },
    brand: { flexDirection: 'row', alignItems: 'center', gap: 12 },
    logo: {
      width: 40,
      height: 40,
      borderRadius: 12,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.primary,
    },
    logoText: { color: theme.onPrimary, fontFamily: FontFamilies.bold, fontSize: 20 },
    brandName: {
      color: theme.text,
      fontFamily: FontFamilies.bold,
      fontSize: 16,
      letterSpacing: 0.6,
    },
    brandCaption: { ...label, fontSize: 10, marginTop: 2 },
    account: { flexDirection: 'row', alignItems: 'center', gap: 16 },
    accountText: { alignItems: 'flex-end' },
    professionalName: { color: theme.text, fontFamily: FontFamilies.semibold, fontSize: 15 },
    professionalCrm: { ...label, marginTop: 2 },
    body: { flex: 1, gap: 20, padding: 20 },
    bodyWide: { paddingHorizontal: 40, paddingTop: 28 },
    titleRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      flexWrap: 'wrap',
      gap: 16,
    },
    titleBlock: { flexShrink: 1, gap: 6 },
    title: { color: theme.text, fontFamily: FontFamilies.bold, fontSize: 28 },
    subtitle: { color: theme.textSecondary, fontFamily: FontFamilies.regular, fontSize: 15 },
    toolbar: { flexDirection: 'row', alignItems: 'center', flexWrap: 'wrap', gap: 12 },
    search: {
      flexGrow: 1,
      flexBasis: 320,
      minHeight: 48,
      paddingHorizontal: 16,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: theme.border,
      backgroundColor: theme.field,
      color: theme.text,
      fontFamily: FontFamilies.regular,
      fontSize: 15,
    },
    toolbarActions: { flexDirection: 'row', flexWrap: 'wrap', gap: 12 },
    primaryButton: { ...button, minHeight: 52, backgroundColor: theme.primary },
    primaryButtonText: { color: theme.onPrimary, fontFamily: FontFamilies.semibold, fontSize: 16 },
    outlineButton: {
      ...button,
      borderWidth: 1.5,
      borderColor: theme.primary,
      backgroundColor: theme.surface,
    },
    outlineButtonText: { color: theme.primary, fontFamily: FontFamilies.semibold, fontSize: 15 },
    disabledButton: { borderColor: theme.border, backgroundColor: theme.field },
    disabledButtonText: { color: theme.placeholder },
    textButton: { ...button, paddingHorizontal: 8 },
    textButtonText: { color: theme.primary, fontFamily: FontFamilies.semibold, fontSize: 15 },
    pressed: { opacity: 0.82 },
    listCard: {
      flex: 1,
      overflow: 'hidden',
      borderRadius: 20,
      backgroundColor: theme.surface,
    },
    columnHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 16,
      paddingHorizontal: 32,
      paddingVertical: 14,
      borderBottomWidth: 1,
      borderBottomColor: theme.border,
    },
    columnLabel: label,
    row: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 16,
      paddingHorizontal: 20,
      paddingVertical: 10,
    },
    rowMain: {
      flex: 1,
      minHeight: 52,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 16,
      paddingHorizontal: 12,
      borderRadius: 12,
    },
    colName: { flex: 2.4 },
    colRecord: { flex: 1.1 },
    colBirth: { flex: 1.2 },
    colLastExam: { flex: 1.4, alignItems: 'flex-start', gap: 4 },
    colCount: { flex: 0.6, textAlign: 'center' },
    colAction: { width: 116 },
    patientName: { color: theme.text, fontFamily: FontFamilies.semibold, fontSize: 16 },
    cell: { color: theme.text, fontFamily: FontFamilies.regular, fontSize: 15 },
    cellSecondary: { color: theme.textSecondary, fontFamily: FontFamilies.regular, fontSize: 13 },
    record: { color: theme.textSecondary, fontFamily: FontFamilies.regular, fontSize: 15 },
    count: { color: theme.text, fontFamily: FontFamilies.semibold, fontSize: 15 },
    chip: { paddingHorizontal: 10, paddingVertical: 3, borderRadius: 12 },
    chipText: { fontFamily: FontFamilies.semibold, fontSize: 12 },
    chipConcluido: { backgroundColor: theme.background },
    chipConcluidoText: { color: theme.text },
    chipInterrompido: { backgroundColor: BrandPalette.lightPeach },
    chipInterrompidoText: { color: theme.primary },
    chipRecusado: { backgroundColor: BrandPalette.cream },
    chipRecusadoText: { color: BrandPalette.deepWine },
    rowExport: { ...button, minHeight: 40, paddingHorizontal: 16 },
    separator: { height: 1, marginHorizontal: 24, backgroundColor: theme.border },
    empty: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 12, padding: 32 },
    emptyIcon: {
      width: 88,
      height: 88,
      borderRadius: 44,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: BrandPalette.lightPeach,
    },
    emptyIconText: { color: theme.primary, fontFamily: FontFamilies.bold, fontSize: 36 },
    emptyTitle: { color: theme.text, fontFamily: FontFamilies.bold, fontSize: 22 },
    emptyText: {
      color: theme.textSecondary,
      fontFamily: FontFamilies.regular,
      fontSize: 15,
      textAlign: 'center',
    },
    noResults: {
      padding: 32,
      color: theme.textSecondary,
      fontFamily: FontFamilies.regular,
      fontSize: 15,
      textAlign: 'center',
    },
  });
}

export type HomeStyles = ReturnType<typeof createHomeStyles>;
